# Generated by Django 4.0.4 on 2022-05-08 07:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Baza_Fuqaro',
            fields=[
                ('jshir', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='JSHIR')),
                ('berilgan_joy', models.CharField(max_length=200)),
                ('pass_seriya', models.CharField(max_length=8, verbose_name='Passport seriyasi')),
                ('pass_raqam', models.IntegerField(verbose_name='Passport seriyasi')),
                ('pass_berilgan_sana', models.DateField()),
                ('pass_amal_muddati', models.DateField()),
                ('ism', models.CharField(max_length=80)),
                ('familiya', models.CharField(max_length=80)),
                ('sharif', models.CharField(max_length=80)),
                ('tug_sana', models.DateField()),
                ('guvohnoma_seriya', models.CharField(max_length=30, verbose_name='guvohnoma seriyasi')),
                ('guvohnoma_raqam', models.IntegerField(verbose_name='guvohnoma seriyasi')),
                ('guvohnoma_sana', models.DateField()),
                ('guvohnoma_berilgan_joy', models.CharField(max_length=200)),
                ('hujjat_turi', models.SmallIntegerField(verbose_name='Hujjat turi')),
                ('jins', models.SmallIntegerField(verbose_name='tuman')),
                ('holati', models.SmallIntegerField(verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'BazaFuqaro',
                'verbose_name_plural': 'BazaFuqarolar',
            },
        ),
        migrations.CreateModel(
            name='BazaUsmir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(verbose_name='branch')),
                ('jshir', models.BigIntegerField(blank=True, null=True, verbose_name='JSHIR')),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('qfy_code', models.IntegerField(blank=True, null=True, verbose_name='QFY code')),
                ('familiya', models.CharField(blank=True, max_length=60, null=True)),
                ('ism', models.CharField(blank=True, max_length=60, null=True)),
                ('sharif', models.CharField(blank=True, max_length=60, null=True)),
                ('jins_code', models.SmallIntegerField(blank=True, null=True, verbose_name='Jins kodi')),
                ('jins_nomi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Jins Nomi')),
                ('tugilgan_kun', models.DateField(blank=True, null=True)),
                ('vazni', models.SmallIntegerField(blank=True, null=True)),
                ('buyi', models.SmallIntegerField(blank=True, null=True)),
                ('cert_num', models.CharField(blank=True, max_length=60, null=True, verbose_name='Cert_num')),
                ('cert_date', models.DateField(blank=True, null=True)),
                ('cert_place', models.IntegerField(blank=True, null=True, verbose_name='Cert Place')),
                ('ota_familiya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining Familiyasi')),
                ('ota_ism', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi')),
                ('ota_sharif', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining Sharifi')),
                ('ota_tug_sana', models.DateField(blank=True, null=True, verbose_name='Otasining tug`ilgan sanasi')),
                ('ona_familiya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Onasining Familiyasi')),
                ('ona_ism', models.CharField(blank=True, max_length=100, null=True, verbose_name='Onasining ismi')),
                ('ona_sharif', models.CharField(blank=True, max_length=60, null=True, verbose_name='Onasining Sharifi')),
                ('ona_tug_sana', models.DateField(blank=True, null=True, verbose_name='Onasining tug`ilgan sanasi')),
                ('ona_passport_seriyasi', models.CharField(blank=True, max_length=2, null=True, verbose_name='Onasining Pasport seriyasi')),
                ('ona_passport_raqami', models.SmallIntegerField(blank=True, null=True, verbose_name='Onasining Pasport raqami')),
                ('guvohnoma_seriyasi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Guvohnoma seriyasi')),
                ('guvohnoma_raqami', models.SmallIntegerField(blank=True, null=True, verbose_name='Guvohnoma raqami')),
                ('guvohnoma_berilgan_sana', models.DateField(blank=True, null=True, verbose_name='Guvohnoma berilgan sanasi')),
                ('ota_jshir', models.BigIntegerField(blank=True, null=True, verbose_name='Ota JSHIR')),
                ('ona_jshir', models.BigIntegerField(blank=True, null=True, verbose_name='Ona JSHIR')),
                ('ota_passport_seriyasi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Otasining Pasport seriyasi')),
                ('ota_passport_raqami', models.SmallIntegerField(blank=True, null=True, verbose_name='Otasining Pasport raqami')),
                ('ota_passport_berilgan_vaqti', models.DateField(blank=True, null=True, verbose_name='Otasining pasport berilgan vaqti')),
                ('doc_num', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doc_num')),
            ],
            options={
                'verbose_name': 'BazaUsmir',
                'verbose_name_plural': 'BazaUsmirlar',
            },
        ),
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
            },
        ),
        migrations.CreateModel(
            name='Fuqaro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jshirr', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999), django.core.validators.MinValueValidator(10000000000000)], verbose_name='JSHIR')),
                ('familiya', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=30)),
                ('sharif', models.CharField(max_length=30)),
                ('tug_sana', models.DateField()),
                ('pass_seriya', models.CharField(max_length=2, verbose_name='Passport seriyasi')),
                ('pass_raqam', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1000000)], verbose_name='Passport seriyasi')),
                ('pass_berilgan_sana', models.DateField()),
                ('doimiy_manzil', models.CharField(blank=True, max_length=250, null=True, verbose_name='Doimiy yashash manzili')),
                ('doimiy_hozirgi_manzil', models.BooleanField(blank=True, default=True)),
                ('status', models.BooleanField(default=True)),
                ('migrant', models.BooleanField(blank=True, default=False, null=True)),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi')),
            ],
            options={
                'verbose_name': 'Fuqaro',
                'verbose_name_plural': 'Fuqarolar',
            },
        ),
        migrations.CreateModel(
            name='Fuqarolik_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Fuqarolik turi')),
            ],
            options={
                'verbose_name': 'Fuqarolik turi',
                'verbose_name_plural': 'Fuqarolik turlari',
            },
        ),
        migrations.CreateModel(
            name='Holat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Holat',
                'verbose_name_plural': 'Holatlar',
            },
        ),
        migrations.CreateModel(
            name='Jins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='Jinsi')),
            ],
            options={
                'verbose_name': 'Jins',
                'verbose_name_plural': 'Jinslar',
            },
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Mahalla')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
            },
        ),
        migrations.CreateModel(
            name='Millat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Millati')),
            ],
            options={
                'verbose_name': 'Millat',
                'verbose_name_plural': 'Millatlar',
            },
        ),
        migrations.CreateModel(
            name='mkb10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.CharField(max_length=15)),
                ('r_parent', models.CharField(blank=True, max_length=15, null=True)),
                ('r_level', models.SmallIntegerField()),
                ('row_num', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('include', models.TextField(blank=True, null=True)),
                ('exclude', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('s_group', models.BooleanField(default=False)),
                ('F_Print', models.BooleanField(default=False)),
                ('R3', models.CharField(max_length=3)),
                ('ER3', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'mkb10',
                'verbose_name_plural': 'mkb10',
            },
        ),
        migrations.CreateModel(
            name='Tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('tuman_tashkilotimi', models.BooleanField(default=True, verbose_name='Tuman tashkilotimi yoki viliya?')),
                ('login', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('parol', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('oldingi_id', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='fuqaro.tashkilot')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlari',
            },
        ),
        migrations.CreateModel(
            name='Tashkilot_tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tashkilot turi',
                'verbose_name_plural': 'Tashkilot turlari',
            },
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Viloyat')),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.davlat', verbose_name='davlat')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='Usmir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=30)),
                ('sharif', models.CharField(max_length=30)),
                ('tug_sana', models.DateField()),
                ('guvohnoma_seriya', models.CharField(max_length=10, verbose_name='guvohnoma seriyasi')),
                ('guvohnoma_raqam', models.SmallIntegerField(verbose_name='guvohnoma seriyasi')),
                ('status', models.BooleanField(default=True)),
                ('migrant', models.BooleanField(default=False)),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi')),
                ('guvohnoma_kim_bergan_tuman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.tuman', verbose_name='tuman')),
                ('jins_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.jins', verbose_name='tuman')),
                ('millat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.millat', verbose_name='Millat')),
                ('tug_joy_davlat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.davlat', verbose_name="Tug'ulgan davlati")),
                ('tug_joy_tuman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman', verbose_name="Tug'ulgan tumani")),
            ],
            options={
                'verbose_name': 'O`smir',
                'verbose_name_plural': 'O`smirlar',
            },
        ),
        migrations.AddField(
            model_name='tuman',
            name='viloyat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.viloyat', verbose_name='viloyat'),
        ),
        migrations.CreateModel(
            name='Tashkilot_Tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20, verbose_name='Tashkilot telefon raqami')),
                ('tashkilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Tashkilot nomi')),
            ],
            options={
                'verbose_name': 'Tashkilot telefon raqami',
                'verbose_name_plural': 'Tashkilotlar telefon raqamilari',
            },
        ),
        migrations.CreateModel(
            name='Tashkilot_qushimcha_malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuqarolari_soni', models.IntegerField(blank=True, null=True)),
                ('oila_soni', models.IntegerField(blank=True, null=True)),
                ('tashkilot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Tashkilot nomi')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlari',
            },
        ),
        migrations.AddField(
            model_name='tashkilot',
            name='tashkilot_turi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot_tur', verbose_name='Tashkilot turi'),
        ),
        migrations.AddField(
            model_name='tashkilot',
            name='tuman_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman', verbose_name='Tuman nomi'),
        ),
        migrations.CreateModel(
            name='Mahalla_op',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mahalla', verbose_name='Biriktirilgan maxallalar')),
                ('tashkilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Tashkiloti')),
            ],
            options={
                'verbose_name': 'Biriktirilgan maxallalar ',
                'verbose_name_plural': 'Biriktirilgan maxallalar',
            },
        ),
        migrations.AddField(
            model_name='mahalla',
            name='tuman_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman', verbose_name='tuman'),
        ),
        migrations.CreateModel(
            name='Kucha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Kucha')),
                ('mahalla_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mahalla', verbose_name='mahalla')),
            ],
            options={
                'verbose_name': 'Kucha',
                'verbose_name_plural': 'Kuchalar',
            },
        ),
        migrations.CreateModel(
            name='Fuqaro_tashqi_kiritilgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuqaro_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro')),
                ('fuqarolik_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi')),
            ],
            options={
                'verbose_name': 'Tashqi kiritilgan fuqaro',
                'verbose_name_plural': 'Tashqi kiritilgan fuqarolar',
            },
        ),
        migrations.CreateModel(
            name='Fuqaro_Jshir_Takror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jshir', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999999), django.core.validators.MinValueValidator(10000000000000)], verbose_name='JSHIR')),
                ('familiya', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=30)),
                ('sharif', models.CharField(max_length=30)),
                ('tug_sana', models.DateField()),
                ('pass_seriya', models.CharField(max_length=2, verbose_name='Passport seriyasi')),
                ('pass_raqam', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1000000)], verbose_name='Passport seriyasi')),
                ('pass_berilgan_sana', models.DateField()),
                ('doimiy_manzil', models.CharField(blank=True, max_length=250, null=True, verbose_name='Doimiy yashash manzili')),
                ('doimiy_hozirgi_manzil', models.BooleanField(blank=True, default=True)),
                ('status', models.BooleanField(default=True)),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi')),
                ('doimiy_kucha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha', verbose_name="Doimiy yashash ko'chasi")),
                ('doimiy_mahalla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mahalla', verbose_name='Doimiy yashash mahallasi')),
                ('doimiy_tuman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.tuman', verbose_name='Doimiy yashash tumani')),
                ('doimiy_viloyat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.viloyat', verbose_name='Doimiy yashash viloyati')),
                ('jins', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.jins', verbose_name='Jinsi')),
                ('millat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.millat', verbose_name='Millat')),
                ('pass_kim_bergan_tuman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.tuman', verbose_name='Passport bergan tuman')),
                ('tug_joy_davlat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.davlat', verbose_name="Tug'ulgan davlati")),
                ('tug_joy_tuman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.tuman', verbose_name="Tug'ulgan tumani")),
            ],
            options={
                'verbose_name': 'Takror kiritilgan fuqaro',
                'verbose_name_plural': 'Takror kiritilgan fuqarolar',
            },
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='doimiy_kucha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha', verbose_name="Doimiy yashash ko'chasi"),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='doimiy_mahalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mahalla', verbose_name='Doimiy yashash mahallasi'),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='doimiy_tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.tuman', verbose_name='Doimiy yashash tumani'),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='doimiy_viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.viloyat', verbose_name='Doimiy yashash viloyati'),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='jins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.jins', verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='millat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.millat', verbose_name='Millat'),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='pass_kim_bergan_tuman_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.tuman', verbose_name='Passport bergan tuman'),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='tug_joy_davlat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.davlat', verbose_name="Tug'ulgan davlati"),
        ),
        migrations.AddField(
            model_name='fuqaro',
            name='tug_joy_tuman_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.tuman', verbose_name="Tug'ulgan tumani"),
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('tashkilot_turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuqaro.tashkilot_tur', verbose_name='Tashkilot Turi')),
            ],
            options={
                'verbose_name': 'Lavozim Group',
                'verbose_name_plural': 'Lavozim Groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChetElFuqarosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujjatning_seriyasi_raqami', models.CharField(max_length=30)),
                ('familiya', models.CharField(max_length=50, verbose_name='Familiyasi')),
                ('ism', models.CharField(max_length=50, verbose_name='Ismi')),
                ('sharif', models.CharField(max_length=50, verbose_name='Sharifi')),
                ('tug_sana', models.DateField(verbose_name='Tug`ilgan sanasi')),
                ('vaqtinchalik_manzil', models.CharField(max_length=100)),
                ('qushilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilgan_sana', models.DateTimeField(auto_now=True)),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi')),
                ('fuqaroligi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.davlat', verbose_name='Fuqaroligi')),
                ('jins', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.jins', verbose_name='Jins')),
                ('vaqtinchalik_kucha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha')),
                ('vaqtinchalik_mahalla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mahalla')),
                ('vaqtinchalik_tuman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman')),
                ('vaqtinchalik_viloyat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.viloyat')),
            ],
            options={
                'verbose_name': 'Chet El Fuqarosi',
                'verbose_name_plural': 'Chet El Fuqarosi',
            },
        ),
        migrations.CreateModel(
            name='Boshqa_manzili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yashash_manzili', models.CharField(blank=True, max_length=200, null=True, verbose_name='yashash manzili')),
                ('fuqaro_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro', verbose_name='fuqaro id si')),
                ('yashash_kucha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha', verbose_name="fuqaro  yashash ko'chasi")),
                ('yashash_mahalla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mahalla', verbose_name='fuqaro  yashash Mahalla')),
                ('yashash_tuman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman', verbose_name='fuqaro  yashash Tuman')),
                ('yashash_viloyat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.viloyat', verbose_name='fuqaro  yashash viloyati')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='tashkilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Qaysi Tashkilotda ishlaydi '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
