# Generated by Django 4.0.4 on 2022-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza_fuqaro',
            name='jshir',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='JSHIR'),
        ),
    ]
