# Generated by Django 4.0.4 on 2022-05-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0002_alter_baza_fuqaro_jshir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ona_passport_seriyasi',
            new_name='ona_pasport_seriya',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ona_jshir',
            new_name='ona_shir',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_passport_berilgan_vaqti',
            new_name='ota_pasport_berilgan_vaqti',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_passport_raqami',
            new_name='ota_pasport_raqami',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_passport_seriyasi',
            new_name='ota_pasport_seriya',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_jshir',
            new_name='ota_shir',
        ),
    ]
