# Generated by Django 4.0.4 on 2022-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0004_rename_ona_pasport_seriya_bazausmir_ona_pasport_seriya1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazausmir',
            name='guvohnoma_raqami',
            field=models.IntegerField(blank=True, null=True, verbose_name='Guvohnoma raqami'),
        ),
    ]
