# Generated by Django 4.0.4 on 2022-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0005_alter_bazausmir_guvohnoma_raqami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazausmir',
            name='buyi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bazausmir',
            name='jins_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jins kodi'),
        ),
        migrations.AlterField(
            model_name='bazausmir',
            name='ona_passport_raqami',
            field=models.IntegerField(blank=True, null=True, verbose_name='Onasining Pasport raqami'),
        ),
        migrations.AlterField(
            model_name='bazausmir',
            name='vazni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
