# Generated by Django 4.0.4 on 2022-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0006_alter_bazausmir_buyi_alter_bazausmir_jins_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazausmir',
            name='guvohnoma_raqami',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Guvohnoma raqami'),
        ),
    ]
