# Generated by Django 4.0.4 on 2022-05-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0007_alter_bazausmir_guvohnoma_raqami'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ona_pasport_seriya1',
            new_name='ona_pasport_seriya',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_pasport_raqami1',
            new_name='ota_pasport_raqami2',
        ),
    ]
