# Generated by Django 4.0.4 on 2022-05-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0008_rename_ona_pasport_seriya1_bazausmir_ona_pasport_seriya_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ona_shir1',
            new_name='ona_shir',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_pasport_raqami2',
            new_name='ota_pasport_raqami',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_pasport_seriya1',
            new_name='ota_pasport_seriya',
        ),
        migrations.RenameField(
            model_name='bazausmir',
            old_name='ota_shir1',
            new_name='ota_shir',
        ),
    ]
