# Generated by Django 4.0.4 on 2022-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0009_rename_ona_shir1_bazausmir_ona_shir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chetelfuqarosi',
            name='vaqtinchalik_manzil',
            field=models.TextField(),
        ),
    ]
