# Generated by Django 4.0.4 on 2022-05-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0010_alter_chetelfuqarosi_vaqtinchalik_manzil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chetelfuqarosi',
            name='vaqtinchalik_kucha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha'),
        ),
        migrations.AlterField(
            model_name='chetelfuqarosi',
            name='vaqtinchalik_mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mahalla'),
        ),
    ]
