# Generated by Django 4.0.4 on 2022-05-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0013_rename_jshirr_fuqaro_jshir_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuqaro',
            old_name='jshir',
            new_name='jshirr',
        ),
    ]
