# Generated by Django 4.0.4 on 2022-05-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0014_rename_jshir_fuqaro_jshirr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuqaro',
            old_name='jshirr',
            new_name='jshir',
        ),
    ]
