# Generated by Django 4.0.4 on 2022-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0015_rename_jshirr_fuqaro_jshir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuqaro',
            name='doimiy_manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Doimiy yashash manzili'),
        ),
    ]
