# Generated by Django 4.0.4 on 2022-05-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0016_alter_fuqaro_doimiy_manzil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuqaro_jshir_takror',
            old_name='jshir',
            new_name='jshirr',
        ),
    ]
