# Generated by Django 4.0.4 on 2022-05-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0017_rename_jshir_fuqaro_jshir_takror_jshirr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuqaro',
            old_name='jshir',
            new_name='jshirr',
        ),
        migrations.RenameField(
            model_name='fuqaro_jshir_takror',
            old_name='jshirr',
            new_name='jshir',
        ),
    ]
