# Generated by Django 4.0.4 on 2022-05-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0018_rename_jshir_fuqaro_jshirr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usmir',
            old_name='jins_id',
            new_name='jins',
        ),
    ]
