# Generated by Django 4.0.4 on 2022-05-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0019_rename_jins_id_usmir_jins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usmir',
            name='guvohnoma_raqam',
            field=models.IntegerField(verbose_name='guvohnoma seriyasi'),
        ),
    ]
