# Generated by Django 4.0.4 on 2022-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0021_alter_usmir_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usmir',
            name='familiya',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usmir',
            name='ism',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usmir',
            name='sharif',
            field=models.CharField(max_length=300),
        ),
    ]
