# Generated by Django 4.0.4 on 2022-05-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0024_alter_usmir_familiya_alter_usmir_ism_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuqaro',
            old_name='jshirr',
            new_name='jshir',
        ),
    ]
