# Generated by Django 4.0.4 on 2022-05-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0026_alter_davlat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baza_fuqaro',
            options={'ordering': ['jshir'], 'verbose_name': 'BazaFuqaro', 'verbose_name_plural': 'BazaFuqarolar'},
        ),
        migrations.AlterModelOptions(
            name='chetelfuqarosi',
            options={'ordering': ['-qushilgan_sana'], 'verbose_name': 'Chet El Fuqarosi', 'verbose_name_plural': 'Chet El Fuqarosi'},
        ),
        migrations.AlterModelOptions(
            name='fuqaro',
            options={'ordering': ['-qushulgan_sana'], 'verbose_name': 'Fuqaro', 'verbose_name_plural': 'Fuqarolar'},
        ),
        migrations.AlterModelOptions(
            name='fuqaro_jshir_takror',
            options={'ordering': ['-qushulgan_sana'], 'verbose_name': 'Takror kiritilgan fuqaro', 'verbose_name_plural': 'Takror kiritilgan fuqarolar'},
        ),
        migrations.AlterModelOptions(
            name='fuqaro_tashqi_kiritilgan',
            options={'ordering': ['fuqaro_id'], 'verbose_name': 'Tashqi kiritilgan fuqaro', 'verbose_name_plural': 'Tashqi kiritilgan fuqarolar'},
        ),
        migrations.AlterModelOptions(
            name='fuqarolik_turi',
            options={'ordering': ['name'], 'verbose_name': 'Fuqarolik turi', 'verbose_name_plural': 'Fuqarolik turlari'},
        ),
        migrations.AlterModelOptions(
            name='holat',
            options={'ordering': ['name'], 'verbose_name': 'Holat', 'verbose_name_plural': 'Holatlar'},
        ),
        migrations.AlterModelOptions(
            name='mahalla_op',
            options={'ordering': ['tashkilot'], 'verbose_name': 'Biriktirilgan maxallalar ', 'verbose_name_plural': 'Biriktirilgan maxallalar'},
        ),
        migrations.AlterModelOptions(
            name='millat',
            options={'ordering': ['name'], 'verbose_name': 'Millat', 'verbose_name_plural': 'Millatlar'},
        ),
        migrations.AlterModelOptions(
            name='mkb10',
            options={'ordering': ['r'], 'verbose_name': 'mkb10', 'verbose_name_plural': 'mkb10'},
        ),
        migrations.AlterModelOptions(
            name='tashkilot',
            options={'ordering': ['nomi'], 'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlari'},
        ),
        migrations.AlterModelOptions(
            name='tashkilot_qushimcha_malumot',
            options={'ordering': ['tashkilot_id'], 'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlari'},
        ),
        migrations.AlterModelOptions(
            name='tashkilot_tel',
            options={'ordering': ['tashkilot_id'], 'verbose_name': 'Tashkilot telefon raqami', 'verbose_name_plural': 'Tashkilotlar telefon raqamilari'},
        ),
        migrations.AlterModelOptions(
            name='tashkilot_tur',
            options={'ordering': ['name'], 'verbose_name': 'Tashkilot turi', 'verbose_name_plural': 'Tashkilot turlari'},
        ),
        migrations.AlterModelOptions(
            name='usmir',
            options={'ordering': ['-qushulgan_sana'], 'verbose_name': 'O`smir', 'verbose_name_plural': 'O`smirlar'},
        ),
        migrations.AlterModelOptions(
            name='viloyat',
            options={'ordering': ['name'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
    ]
