# Generated by Django 4.0.4 on 2022-05-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0028_usmir_baza_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usmir',
            name='baza_status',
        ),
    ]
