# Generated by Django 4.0.4 on 2022-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinamikKuzatuvchiGuruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Dinamik Kuzatuvchi Guruh',
                'verbose_name_plural': 'Dinamik Kuzatuvchi Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='IjtimoiyHolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ijtimoiy Holati',
                'verbose_name_plural': 'Ijtimoiy Holatlar',
            },
        ),
        migrations.CreateModel(
            name='Malumoti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Ma`lumot',
                'verbose_name_plural': 'Ma`lumoti',
            },
        ),
        migrations.CreateModel(
            name='Nogironlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Nogironlik',
                'verbose_name_plural': 'Nogironliklar',
            },
        ),
        migrations.CreateModel(
            name='OilaviySharoiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Oilaviy Sharoit',
                'verbose_name_plural': 'Oilaviy Sharoitlar',
            },
        ),
        migrations.CreateModel(
            name='TirikchilikManbasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tirikchilik Manbasi',
                'verbose_name_plural': 'Tirikchilik Manbalari',
            },
        ),
    ]
