# Generated by Django 4.0.4 on 2022-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UchotChiqarishSababi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Uchot chiqarish sababi',
                'verbose_name_plural': 'Uchot chiqarish sabablari',
            },
        ),
    ]
