# Generated by Django 4.0.4 on 2022-05-08 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuqaro', '0001_initial'),
        ('helper_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TashkilotPisxEndoQushimcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuqarolari_soni', models.PositiveSmallIntegerField(verbose_name='Fuqarolari soni')),
                ('qandli_diabet_1_tur', models.PositiveSmallIntegerField(verbose_name='qandli diabet 1-tur')),
                ('qandli_diabet_2_tur', models.PositiveSmallIntegerField(verbose_name='qandli diabet 2-tur')),
                ('qandsiz_diabet', models.PositiveSmallIntegerField(verbose_name='qandsiz diabet')),
                ('gipotireoz', models.PositiveSmallIntegerField(verbose_name='gipotireoz')),
                ('diffuz_toksik_buqoq', models.PositiveSmallIntegerField(verbose_name='diffuz toksik buqoq')),
                ('tugunli_buqoq', models.PositiveSmallIntegerField(verbose_name='tugunli buqoq')),
                ('somatotrop_yetishmovchilik', models.PositiveSmallIntegerField(verbose_name='somatotrop yetishmovchilik')),
                ('jinsiy_balogatga_kechikish', models.PositiveSmallIntegerField(verbose_name='jinsiy balogatga kechikish')),
                ('akromegaliya', models.PositiveSmallIntegerField(verbose_name='akromegaliya')),
                ('semizlik', models.PositiveSmallIntegerField(verbose_name='semizlik')),
                ('boshqa', models.PositiveSmallIntegerField(verbose_name='boshqa')),
                ('tashkilot_p_endo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Tashkilot nomi')),
            ],
            options={
                'verbose_name': "Tashkilotning qo'shimcha ma'lumotlari",
                'verbose_name_plural': "Tashkilotlarning qo'shimcha ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Shir_takror_psix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farzandlari_soni', models.SmallIntegerField(blank=True, null=True)),
                ('ish_joyi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish Joyi')),
                ('tashxis_sana', models.DateField(blank=True, null=True, verbose_name='Tashxis Sana')),
                ('dispanser_holati', models.BooleanField(default=False, verbose_name='Dispanser Holati')),
                ('kasallik_bosh_sana', models.DateField(blank=True, null=True, verbose_name='Kasallik Boshlangan Sana')),
                ('d_nazoratga_olingan_sana', models.DateField(verbose_name='Dinamik nazoratga olingan sana')),
                ('jamoatga_xavf', models.BooleanField(default=False, verbose_name='Jamoatga xavf')),
                ('jamoatga_xavf_text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Jamoatga xavf Text')),
                ('shifoxonaga_yotish_soni', models.SmallIntegerField(blank=True, null=True, verbose_name='Shifoxonaga yotish soni')),
                ('majburiy_davo_shifoxonasi', models.SmallIntegerField(blank=True, null=True, verbose_name='Majburiy davo shifoxonasi')),
                ('hisobga_olish_kim_yuborgan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hisobga olish kim yuborgan')),
                ('tashxis_mkb10_text', models.CharField(max_length=30, verbose_name='Tashxis mkb10 ID')),
                ('holati', models.BooleanField(default=True, verbose_name='Holati')),
                ('hisobdan_chiqarish_sana', models.DateField(blank=True, null=True, verbose_name='Hisobdan chiqarilgan sana')),
                ('nechanchi_sinf_uqigan', models.SmallIntegerField(blank=True, null=True, verbose_name='Nechanchi sinf o`qigan')),
                ('uqiydi', models.BooleanField(default=False)),
                ('add_tashkilot_id', models.IntegerField(verbose_name='Kirituvchi Tashkilot')),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('chetel_fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.chetelfuqarosi', verbose_name='chetel fuqaro id')),
                ('dinamik_kuzatuv_guruhi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helper_app.dinamikkuzatuvchiguruh', verbose_name='Dinamik Kuzatuvchi guruh')),
                ('fuqaro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro_jshir_takror', verbose_name='Fuqaro id')),
                ('fuqarolik_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi', verbose_name='Fuqarolik Turi')),
                ('hisobdan_chiqarish_sababi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.mkb10', verbose_name='Hisobdan chiqarilgan sababi mkb10')),
                ('hisobdan_chiqarishgan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Hisobdan chiqarilgan user ID')),
                ('malumoti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helper_app.malumoti', verbose_name='Ma`lumoti')),
                ('nogironlik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.nogironlik', verbose_name='Nogironlik ID')),
                ('oilaviy_sharoiti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.oilaviysharoiti', verbose_name='Oilaviy Sharoiti')),
                ('tashxis_mkb10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mkb10', verbose_name='Tashxis mkb10 ID')),
                ('tirikchilik_manbasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.tirikchilikmanbasi', verbose_name='Tirikchilik Manbasi')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman', verbose_name='Tuman ID')),
            ],
            options={
                'verbose_name': 'Asosiy',
                'verbose_name_plural': 'Asosiy',
            },
        ),
        migrations.CreateModel(
            name='ShifoxonagaYotkazish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qayd_raqami', models.IntegerField(verbose_name='Qayd raqami')),
                ('kelgan_sana', models.DateField(verbose_name='Kelgan Sanasi')),
                ('ketgan_sana', models.DateField(verbose_name='Ketgan Sanasi')),
                ('qushilgan_sana', models.DateField(auto_now_add=True, verbose_name='Qushilgan Sana')),
                ('fuqari_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro', verbose_name='Fuqaro id')),
                ('qushgan_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi')),
                ('tashxis_mkb10_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mkb10', verbose_name='Tashxis mkb10 ID')),
            ],
            options={
                'verbose_name': 'Shifoxonaga Yotkazish',
                'verbose_name_plural': 'Shifoxonaga Yotkazishlar',
            },
        ),
        migrations.CreateModel(
            name='Asosiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farzandlari_soni', models.SmallIntegerField(blank=True, null=True)),
                ('ish_joyi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish Joyi')),
                ('tashxis_sana', models.DateField(blank=True, null=True, verbose_name='Tashxis Sana')),
                ('dispanser_holati', models.BooleanField(default=False, verbose_name='Dispanser Holati')),
                ('kasallik_bosh_sana', models.DateField(blank=True, null=True, verbose_name='Kasallik Boshlangan Sana')),
                ('d_nazoratga_olingan_sana', models.DateField(verbose_name='Dinamik nazoratga olingan sana')),
                ('jamoatga_xavf', models.BooleanField(default=False, verbose_name='Jamoatga xavf')),
                ('jamoatga_xavf_text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Jamoatga xavf Text')),
                ('shifoxonaga_yotish_soni', models.SmallIntegerField(blank=True, null=True, verbose_name='Shifoxonaga yotish soni')),
                ('majburiy_davo_shifoxonasi', models.SmallIntegerField(blank=True, null=True, verbose_name='Majburiy davo shifoxonasi')),
                ('hisobga_olish_kim_yuborgan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hisobga olish kim yuborgan')),
                ('tashxis_mkb10_text', models.CharField(max_length=30, verbose_name='Tashxis mkb10 ID')),
                ('holati', models.BooleanField(default=True, verbose_name='Holati')),
                ('hisobdan_chiqarish_sana', models.DateField(blank=True, null=True, verbose_name='Hisobdan chiqarilgan sana')),
                ('nechanchi_sinf_uqigan', models.SmallIntegerField(blank=True, null=True, verbose_name='Nechanchi sinf o`qigan')),
                ('uqiydi_id', models.BooleanField(default=False)),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('add_tashkilot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Kirituvchi Tashkilot')),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi')),
                ('chetel_fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.chetelfuqarosi', verbose_name='chetel fuqaro id')),
                ('dinamik_kuzatuv_guruhi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helper_app.dinamikkuzatuvchiguruh', verbose_name='Dinamik Kuzatuvchi guruh')),
                ('fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro', verbose_name='Fuqaro id')),
                ('fuqarolik_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi', verbose_name='Fuqarolik Turi')),
                ('hisobdan_chiqarish_sababi_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.mkb10', verbose_name='Hisobdan chiqarilgan sababi mkb10')),
                ('hisobdan_chiqarishgan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Hisobdan chiqarilgan user ID')),
                ('malumoti_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helper_app.malumoti', verbose_name='Ma`lumoti')),
                ('nogironlik_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.nogironlik', verbose_name='Nogironlik ID')),
                ('oilaviy_sharoiti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.oilaviysharoiti', verbose_name='Oilaviy Sharoiti')),
                ('tashxis_mkb10_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mkb10', verbose_name='Tashxis mkb10 ID')),
                ('tirikchilik_manbasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.tirikchilikmanbasi', verbose_name='Tirikchilik Manbasi')),
                ('tuman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman', verbose_name='Tuman ID')),
                ('usmir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.usmir', verbose_name='usmir id')),
            ],
            options={
                'verbose_name': 'Asosiy',
                'verbose_name_plural': 'Asosiy',
            },
        ),
    ]
