# Generated by Django 4.0.4 on 2022-05-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psix_uchot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shir_takror_psix',
            old_name='fuqaro_id',
            new_name='fuqaro',
        ),
    ]
