# Generated by Django 4.0.4 on 2022-05-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psix_uchot', '0002_rename_fuqaro_id_shir_takror_psix_fuqaro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shir_takror_psix',
            old_name='fuqaro',
            new_name='fuqaro_q',
        ),
    ]
