# Generated by Django 4.0.4 on 2022-05-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psix_uchot', '0003_rename_fuqaro_shir_takror_psix_fuqaro_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shir_takror_psix',
            old_name='fuqaro_q',
            new_name='fuqaro',
        ),
    ]
