# Generated by Django 4.0.4 on 2022-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psix_uchot', '0004_rename_fuqaro_q_shir_takror_psix_fuqaro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shir_takror_psix',
            name='fuqaro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fuqaro id'),
        ),
    ]
