# Generated by Django 4.0.4 on 2022-05-12 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0024_alter_usmir_familiya_alter_usmir_ism_and_more'),
        ('helper_app', '0002_uchotchiqarishsababi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psix_uchot', '0006_rename_fuqaro_shir_takror_psix_fuqaro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asosiy',
            name='add_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi'),
        ),
        migrations.AlterField(
            model_name='asosiy',
            name='hisobdan_chiqarishgan_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customuser', to=settings.AUTH_USER_MODEL, verbose_name='Hisobdan chiqarilgan user ID'),
        ),
        migrations.AlterField(
            model_name='shifoxonagayotkazish',
            name='qushgan_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi'),
        ),
        migrations.CreateModel(
            name='Asosiy_psix_uchot_chiqarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farzandlari_soni', models.SmallIntegerField(blank=True, null=True)),
                ('ish_joyi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish Joyi')),
                ('tashxis_sana', models.DateField(blank=True, null=True, verbose_name='Tashxis Sana')),
                ('dispanser_holati', models.BooleanField(default=False, verbose_name='Dispanser Holati')),
                ('kasallik_bosh_sana', models.DateField(blank=True, null=True, verbose_name='Kasallik Boshlangan Sana')),
                ('d_nazoratga_olingan_sana', models.DateField(verbose_name='Dinamik nazoratga olingan sana')),
                ('jamoatga_xavf', models.BooleanField(default=False, verbose_name='Jamoatga xavf')),
                ('jamoatga_xavf_text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Jamoatga xavf Text')),
                ('shifoxonaga_yotish_soni', models.SmallIntegerField(blank=True, null=True, verbose_name='Shifoxonaga yotish soni')),
                ('majburiy_davo_shifoxonasi', models.SmallIntegerField(blank=True, null=True, verbose_name='Majburiy davo shifoxonasi')),
                ('hisobga_olish_kim_yuborgan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hisobga olish kim yuborgan')),
                ('tashxis_mkb10_text', models.CharField(max_length=30, verbose_name='Tashxis mkb10 ID')),
                ('holati', models.BooleanField(default=True, verbose_name='Holati')),
                ('nechanchi_sinf_uqigan', models.SmallIntegerField(blank=True, null=True, verbose_name='Nechanchi sinf o`qigan')),
                ('uqiydi_id', models.BooleanField(default=False)),
                ('qushulgan_sana', models.DateTimeField()),
                ('yangilangan_sana', models.DateTimeField()),
                ('add_tashkilot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Kirituvchi Tashkilot')),
                ('chetel_fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.chetelfuqarosi', verbose_name='chetel fuqaro id')),
                ('dinamik_kuzatuv_guruhi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helper_app.dinamikkuzatuvchiguruh', verbose_name='Dinamik Kuzatuvchi guruh')),
                ('fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro', verbose_name='Fuqaro id')),
                ('fuqarolik_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi', verbose_name='Fuqarolik Turi')),
                ('malumoti_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helper_app.malumoti', verbose_name='Ma`lumoti')),
                ('nogironlik_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.nogironlik', verbose_name='Nogironlik ID')),
                ('oilaviy_sharoiti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.oilaviysharoiti', verbose_name='Oilaviy Sharoiti')),
                ('tashxis_mkb10_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mkb10', verbose_name='Tashxis mkb10 ID')),
                ('tirikchilik_manbasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helper_app.tirikchilikmanbasi', verbose_name='Tirikchilik Manbasi')),
                ('tuman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tuman', verbose_name='Tuman ID')),
                ('usmir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.usmir', verbose_name='usmir id')),
            ],
            options={
                'verbose_name': 'Asosiy_psix_uchot_chiqarish',
                'verbose_name_plural': 'Asosiy_psix_uchot_chiqarishlar',
            },
        ),
    ]
