# Generated by Django 4.0.4 on 2022-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psix_uchot', '0008_asosiy_psix_uchot_chiqarish_uchotdan_chiqargan_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asosiy',
            name='hisobdan_chiqarish_sababi_id',
        ),
        migrations.RemoveField(
            model_name='asosiy',
            name='hisobdan_chiqarish_sana',
        ),
        migrations.RemoveField(
            model_name='asosiy',
            name='hisobdan_chiqarishgan_user',
        ),
        migrations.AddField(
            model_name='asosiy_psix_uchot_chiqarish',
            name='add_user_id',
            field=models.IntegerField(default=1, verbose_name='Kirituvchi'),
        ),
    ]
