# Generated by Django 4.0.4 on 2022-05-12 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuqaro', '0024_alter_usmir_familiya_alter_usmir_ism_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('uchotdan_chiqarish_sababi_text', models.CharField(blank=True, max_length=250, null=True)),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
                ('chetel_fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.chetelfuqarosi', verbose_name='chetel fuqaro Id')),
                ('fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro', verbose_name='Fuqaro Id')),
                ('fuqaro_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi', verbose_name='Fuqarolik turi Id')),
                ('uchotdan_chiqarish_sababi_mkb10_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.mkb10', verbose_name='Hisobdan chiqarilgan sababi mkb10')),
                ('usmir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.usmir', verbose_name='usmir Id')),
            ],
            options={
                'verbose_name': 'UchotTuri',
                'verbose_name_plural': 'UchotTurlari',
            },
        ),
    ]
