# Generated by Django 4.0.4 on 2022-05-08 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuqaro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UchotTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'UchotTuri',
                'verbose_name_plural': 'UchotTurlari',
            },
        ),
        migrations.CreateModel(
            name='uchot_takror_shir_fuqaro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
                ('chetel_fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.chetelfuqarosi', verbose_name='chetel fuqaro Id')),
                ('fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro_jshir_takror', verbose_name='Fuqaro Id')),
                ('fuqaro_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi', verbose_name='Fuqarolik turi Id')),
                ('kucha_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha', verbose_name='Biriktirilgan kucha Id')),
                ('tashkilot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Tashkilot Id')),
                ('uchot_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro_uchot.uchotturi', verbose_name='Uchot Turi Id')),
                ('usmir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.usmir', verbose_name='usmir Id')),
            ],
            options={
                'verbose_name': 'Uchot',
                'verbose_name_plural': 'Uchotdagilar',
            },
        ),
        migrations.CreateModel(
            name='Uchot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('add_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
                ('chetel_fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.chetelfuqarosi', verbose_name='chetel fuqaro Id')),
                ('fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro', verbose_name='Fuqaro Id')),
                ('fuqaro_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi', verbose_name='Fuqarolik turi Id')),
                ('kucha_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha', verbose_name='Biriktirilgan kucha Id')),
                ('tashkilot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Tashkilot Id')),
                ('uchot_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro_uchot.uchotturi', verbose_name='Uchot Turi Id')),
                ('usmir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.usmir', verbose_name='usmir Id')),
            ],
            options={
                'verbose_name': 'Uchot',
                'verbose_name_plural': 'Uchotdagilar',
            },
        ),
    ]
