# Generated by Django 4.0.4 on 2022-05-12 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0024_alter_usmir_familiya_alter_usmir_ism_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuqaro_uchot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UchotChiqarishSababi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Uchot chiqarish sababi',
                'verbose_name_plural': 'Uchot chiqarish sabablari',
            },
        ),
        migrations.AlterField(
            model_name='uchot',
            name='add_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customuserss', to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='uchot_takror_shir_fuqaro',
            name='add_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.CreateModel(
            name='Uchot_chiqarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('qushulgan_sana', models.DateTimeField()),
                ('yangilangan_sana', models.DateTimeField()),
                ('chetel_fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.chetelfuqarosi', verbose_name='chetel fuqaro Id')),
                ('fuqaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqaro', verbose_name='Fuqaro Id')),
                ('fuqaro_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.fuqarolik_turi', verbose_name='Fuqarolik turi Id')),
                ('kucha_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.kucha', verbose_name='Biriktirilgan kucha Id')),
                ('tashkilot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro.tashkilot', verbose_name='Tashkilot Id')),
                ('uchot_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuqaro_uchot.uchotturi', verbose_name='Uchot Turi Id')),
                ('usmir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fuqaro.usmir', verbose_name='usmir Id')),
            ],
            options={
                'verbose_name': 'Uchotdan chiqarish',
                'verbose_name_plural': 'Uchotdan chiqarishlar',
            },
        ),
    ]
