# Generated by Django 4.0.4 on 2022-05-12 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuqaro_uchot', '0003_uchot_chiqarish_uchotdan_chiqargan_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchot_chiqarish',
            name='add_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
            preserve_default=False,
        ),
    ]
