# Generated by Django 4.0.4 on 2022-05-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='qon_bosimi_yuqori',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qon Bosimi Yuqori'),
        ),
    ]
