# Generated by Django 4.0.4 on 2022-05-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0002_alter_qandlidiabetruyxat_qon_bosimi_yuqori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='qon_bosimi_yuqori',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Qon Bosimi Yuqori'),
        ),
    ]
