# Generated by Django 4.0.4 on 2022-05-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0005_alter_qandlidiabetruyxat_analog_insulin_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='analog_insulin_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Analog Insulin h'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='analog_insulin_r',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Analog Insulin r'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='insulin_miqdori_30_70',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Insulin miqdori 30_70'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='insulin_miqdori_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Insulin miqdori h'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='insulin_miqdori_r',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Insulin miqdori r'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='tabletka_biguanid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tabletka biguanid'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='tabletka_glibenklamid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tabletka glibenklamid'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='tabletka_gliklazid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tabletka gliklazid'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='tabletka_glimepirid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tabletka glimepirid'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='tabletka_tiozolidindion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Insulin miqdori h'),
        ),
    ]
