# Generated by Django 4.0.4 on 2022-05-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0006_alter_qandlidiabetruyxat_analog_insulin_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='analog_insulin_h',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Analog Insulin h'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='analog_insulin_r',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Analog Insulin r'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='bel_aylanasi',
            field=models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Bel Aylanasi'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='buyi',
            field=models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Bo`yi'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='insulin_miqdori_30_70',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Insulin miqdori 30_70'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='insulin_miqdori_h',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Insulin miqdori h'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='insulin_miqdori_r',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Insulin miqdori r'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='qon_bosimi_quyi',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Qon Bosimi Quyi'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='qon_bosimi_yuqori',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Qon Bosimi Yuqori'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='tabletka_biguanid',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Tabletka biguanid'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='tabletka_glibenklamid',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Tabletka glibenklamid'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='tabletka_gliklazid',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Tabletka gliklazid'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='tabletka_glimepirid',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Tabletka glimepirid'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='tabletka_tiozolidindion',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Insulin miqdori h'),
        ),
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='vazni',
            field=models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Vazni'),
        ),
    ]
