# Generated by Django 4.0.4 on 2022-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0008_alter_qandli_diabet_ruyxat_shir_takror_analog_insulin_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            name='fuqaro',
            field=models.IntegerField(),
        ),
    ]
