# Generated by Django 4.0.4 on 2022-05-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0009_alter_qandli_diabet_ruyxat_shir_takror_fuqaro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qandli_diabet_ruyxat_shir_takror',
            old_name='fuqaro',
            new_name='fuqaro_id',
        ),
    ]
