# Generated by Django 4.0.4 on 2022-05-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuqaro', '0024_alter_usmir_familiya_alter_usmir_ism_and_more'),
        ('helper_app', '0002_uchotchiqarishsababi'),
        ('qandli_diabet_uchot', '0011_alter_qandlidiabetruyxat_add_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='qushilgan_sana',
        ),
        migrations.RemoveField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='yangilangan_sana',
        ),
        migrations.AddField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='add_user_id',
            field=models.IntegerField(default=1, verbose_name='Oldin Kirituvchi'),
        ),
        migrations.AddField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='uchotdan_chiqarish_sababi',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.PROTECT, related_query_name='UchotChiqarishSababi', to='helper_app.uchotchiqarishsababi', verbose_name='Uchotdan chiqarish sababi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='uchotdan_chiqarish_sababi_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='uchotdan_chiqarish_sababimkb10_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fuqaro.mkb10', verbose_name='Hisobdan chiqarilgan sababi mkb10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat',
            name='endokrinologik_tashxis_mkb10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mkb10_q', to='fuqaro.mkb10', verbose_name='Endokrinologik tashxisi'),
        ),
        migrations.AlterField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='d_nazoratga_olingan_sana',
            field=models.DateField(blank=True, null=True, verbose_name='Dinamik nazoratga olingan sana'),
        ),
    ]
