# Generated by Django 4.0.4 on 2022-05-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qandli_diabet_uchot', '0012_remove_qandlidiabetruyxat_chiqarish_qushilgan_sana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='uchotdan_chiqargan_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi'),
            preserve_default=False,
        ),
    ]
