# Generated by Django 4.0.4 on 2022-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0013_qandlidiabetruyxat_chiqarish_uchotdan_chiqargan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='uchotdan_chiqqan_sana',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
