# Generated by Django 4.0.4 on 2022-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandli_diabet_uchot', '0014_qandlidiabetruyxat_chiqarish_uchotdan_chiqqan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='qandlidiabetruyxat_chiqarish',
            name='qushilgan_sana',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
